# Generated by Django 4.2.5 on 2023-10-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_document_upload_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='upload_sequence',
        ),
    ]
